CREATE TABLE "public"."person" (
  "id" int4 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "fio" varchar(100) NOT NULL UNIQUE,
  "email" varchar(50),
  "birth_year" varchar(4) NOT NULL
);

CREATE TABLE "public"."book" (
  "id" int4 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "name" varchar(100) NOT NULL,
  "author" varchar(100)  NOT NULL,
  "person_id" int4,
  "year" varchar(4)
);

ALTER TABLE "public"."book" ADD CONSTRAINT "fk_book_person" FOREIGN KEY ("person_id") REFERENCES "public"."person" ("id") ON DELETE SET NULL ON UPDATE CASCADE;
